import React,{useEffect,useState}from"react";
import{X,UserCircle,LogIn,UserPlus,LogOut,Wallet,ShieldCheck,Eye,EyeOff}from"lucide-react";
const API_BASE="https://bhai-ai-vpna.onrender.com";
const api=p=>API_BASE+p;
export default function AccountPanel({onClose,onAccount}){
 const[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[account,setAccount]=useState(null),[ledger,setLedger]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[info,setInfo]=useState("");
 const token=()=>localStorage.getItem("bhai_user_session")||sessionStorage.getItem("bhai_user_session")||"";
 async function load(){const t=token();if(!t)return;try{const r=await fetch(api("/api/accounts?me=1"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok){setAccount(d.account);onAccount?.(d.account);const lr=await fetch(api("/api/accounts?ledger=1"),{headers:{Authorization:"Bearer "+t}});const ld=await lr.json();setLedger(ld.ledger||[])}else{localStorage.removeItem("bhai_user_session");sessionStorage.removeItem("bhai_user_session")}}catch{}}
 useEffect(()=>{load()},[]);
 async function submit(){setBusy(true);setError("");setInfo("");try{const action=mode==="login"?"login":"register";const r=await fetch(api("/api/accounts"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");if(action==="register"){setInfo("Account created. Ab login karo.");setMode("login");setPassword("")}else{localStorage.setItem("bhai_user_session",d.session);setAccount(d.account);onAccount?.(d.account);setInfo("Login successful. Free account ready hai.")}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function logout(){const t=token();if(t)await fetch(api("/api/accounts"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})}).catch(()=>{});localStorage.removeItem("bhai_user_session");sessionStorage.removeItem("bhai_user_session");setAccount(null);setActive(null);onAccount?.(null);setInfo("Logged out.")}
 return <div className="panelOverlay"><div className="utilityPanel accountPanel"><div className="utilityHead"><div><b>👤 BHAI X Account</b><span>Free account • Login & access</span></div><button onClick={onClose}><X/></button></div><div className="utilityBody">{account?<><div className="accountHero"><div className="accountAvatar"><UserCircle/></div><div><b>{account.email}</b><span>{account.role} • {account.blocked?"BLOCKED":"ACTIVE"}</span></div></div><div className="creditCard"><Wallet/><div><span>Credits</span><b>{account.credits}</b></div></div><div className="creditCard"><ShieldCheck/><div><span>Plan</span><b>FREE</b><small>Free access enabled</small></div></div><div className="accountLedger"><b>Credit Ledger</b>{ledger.length?ledger.map(x=><div key={x.id}><span>{x.reason||"Credit adjustment"}</span><strong>{x.amount>0?"+":""}{x.amount}</strong></div>):<span>No transactions yet.</span>}</div><button className="accountLogout" onClick={logout}><LogOut size={15}/> Logout</button></>:<><div className="accountTabs"><button className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("");setInfo("")}}><LogIn size={14}/> Login</button><button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setError("");setInfo("")}}><UserPlus size={14}/> Register</button></div><input className="accountInput" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><div className="passwordWrap"><input className="accountInput" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" type={showPassword?"text":"password"} onKeyDown={e=>e.key==="Enter"&&submit()}/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff size={15}/>:<Eye size={15}/>}</button></div><button className="accountPrimary" disabled={busy||!email||password.length<8} onClick={submit}>{mode==="login"?"Login":"Create Account"}</button></>}{error&&<div className="accountError">{error}</div>}{info&&<div className="accountInfo">{info}</div>}<div className="accountNote"><ShieldCheck size={14}/> Free users ke liye account access ready hai. Subscription/payment baad mein enable kiya ja sakta hai.</div></div></div></div>
}