import React,{useEffect,useState}from"react";
import{X,UserCircle,LogIn,UserPlus,LogOut,Wallet,ShieldCheck,Eye,EyeOff,Key,Copy,Trash2,RefreshCw}from"lucide-react";
const API_BASE="https://bhai-ai-vpna.onrender.com";
const api=p=>API_BASE+p;
export default function AccountPanel({onClose,onAccount,ownerOnly=false}){
 const[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[account,setAccount]=useState(null),[ledger,setLedger]=useState([]),[plans,setPlans]=useState([]),[activeSub,setActiveSub]=useState(null),[apiKeys,setApiKeys]=useState([]),[newKey,setNewKey]=useState(null),[keyName,setKeyName]=useState("BHAI-X App"),[keyBusy,setKeyBusy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[info,setInfo]=useState("");
 const token=()=>localStorage.getItem("bhai_user_session")||sessionStorage.getItem("bhai_user_session")||"";
 async function loadPlans(){try{const r=await fetch(api("/api/billing?plans=1"));const d=await r.json();if(r.ok)setPlans(d.plans||[])}catch{}}
 async function loadApiKeys(){const t=token();if(!t)return;try{const r=await fetch(api("/api/api-keys"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok)setApiKeys(d.keys||[])}catch{}}\n async function createApiKey(){const t=token();if(!t||keyBusy)return;setKeyBusy(true);setError("");try{const r=await fetch(api("/api/api-keys"),{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({action:"create",name:keyName,scopes:["chat","coding","github","image","video","files","search","agent"]})});const d=await r.json();if(!r.ok)throw new Error(d.error||"API key creation failed");setNewKey(d.key);setKeyName("BHAI-X App");await loadApiKeys()}catch(e){setError(e.message)}finally{setKeyBusy(false)}}\n async function revokeApiKey(id){const t=token();if(!t)return;try{const r=await fetch(api("/api/api-keys"),{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({action:"revoke",id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Revoke failed");await loadApiKeys()}catch(e){setError(e.message)}}\n async function loadSubscription(){const t=token();if(!t)return;try{const r=await fetch(api("/api/billing"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok)setActiveSub(d.active||null)}catch{}}
 async function load(){const t=token();loadPlans();if(!t)return;try{const r=await fetch(api("/api/accounts?me=1"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok){setAccount(d.account);onAccount?.(d.account);loadApiKeys();const lr=await fetch(api("/api/accounts?ledger=1"),{headers:{Authorization:"Bearer "+t}});const ld=await lr.json();setLedger(ld.ledger||[]);loadSubscription()}else{localStorage.removeItem("bhai_user_session");sessionStorage.removeItem("bhai_user_session")}}catch{}}
 useEffect(()=>{load()},[]);
 async function submit(){setBusy(true);setError("");setInfo("");try{const action=ownerOnly||mode==="login"?"login":"register";const r=await fetch(api("/api/accounts"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");if(action==="register"){setInfo("Account created. Ab login karo.");setMode("login");setPassword("")}else{localStorage.setItem("bhai_user_session",d.session);setAccount(d.account);onAccount?.({...d.account,session:d.session});setInfo("Login successful. Free account ready hai.")}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function logout(){const t=token();if(t)await fetch(api("/api/accounts"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})}).catch(()=>{});localStorage.removeItem("bhai_user_session");sessionStorage.removeItem("bhai_user_session");setAccount(null);onAccount?.(null);setInfo("Logged out.")}
 return <div className="panelOverlay"><div className="utilityPanel accountPanel"><div className="utilityHead"><div><b>🔐 BHAI X Owner Login</b><span>{ownerOnly?"Private owner-only access":"Free account • Login, limits & Upgrade"}</span></div><button onClick={onClose}><X/></button></div><div className="utilityBody">{account?<><div className="accountHero"><div className="accountAvatar"><UserCircle/></div><div><b>{account.email}</b><span>{account.role} • {account.blocked?"BLOCKED":"ACTIVE"}</span></div></div><div className="creditCard"><Wallet/><div><span>Credits</span><b>{account.credits}</b></div></div><div className="creditCard"><ShieldCheck/><div><span>Plan</span><b>{activeSub?"PRO":"FREE"}</b><small>{activeSub?"Active until "+new Date(activeSub.expires_at).toLocaleDateString("en-IN"):"Free access enabled"}</small></div></div>
<div className="subscriptionBox"><div className="subscriptionTitle">⭐ Upgrade to BHAI X Pro</div>
<div className="planGrid">{plans.map(p=><div className="planCard" key={p.id}><b>{p.name}</b><strong>₹{p.amount}</strong><span>{p.days} days</span><small>Higher image/video limits</small><button disabled onClick={()=>setInfo("Payment abhi enable nahi hai. PAN/KYC setup ke baad Upgrade activate karenge.")}>Coming Soon</button></div>)}</div>
<div className="accountNote">Payment abhi disabled hai — koi charge nahi hoga. Plans/UI ready hain.</div></div><div className="apiKeysBox"><div className="subscriptionTitle"><Key size={15}/> BHAI-X API Keys</div><div className="accountNote">Apni apps/scripts ko BHAI-X se connect karne ke liye key banao. Full key sirf creation ke baad yahin dikhegi.</div><div style={{display:"flex",gap:8,marginTop:8}}><input className="accountInput" value={keyName} onChange={e=>setKeyName(e.target.value)} placeholder="Key name"/><button className="accountPrimary" disabled={keyBusy||!keyName.trim()} onClick={createApiKey}>{keyBusy?"Creating…":"Create Key"}</button></div>{newKey&&<div className="apiKeyReveal"><b>⚠️ Copy this key now</b><code>{newKey}</code><button onClick={()=>navigator.clipboard?.writeText(newKey)}><Copy size={14}/> Copy</button><small>Security: full key dobara list mein nahi dikhayi jayegi.</small></div>}{apiKeys.map(k=><div className="apiKeyRow" key={k.id}><div><b>{k.name}</b><small>{k.key_prefix}… • {k.status} • {k.usage_count} uses</small></div>{k.status==="active"&&<button onClick={()=>revokeApiKey(k.id)} title="Revoke"><Trash2 size={14}/></button>}</div>)}</div><div className="accountLedger"><b>Credit Ledger</b>{ledger.length?ledger.map(x=><div key={x.id}><span>{x.reason||"Credit adjustment"}</span><strong>{x.amount>0?"+":""}{x.amount}</strong></div>):<span>No transactions yet.</span>}</div><button className="accountLogout" onClick={logout}><LogOut size={15}/> Logout</button></>:<><div className="accountTabs"><button className="active"><LogIn size={14}/> Owner Login</button>{!ownerOnly&&<button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setError("");setInfo("")}}><UserPlus size={14}/> Register</button>}</div><input className="accountInput" value={email} onChange={e=>setEmail(e.target.value)} placeholder={ownerOnly?"Owner username / email":"Email"} type={ownerOnly?"text":"email"}/><div className="passwordWrap"><input className="accountInput" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" type={showPassword?"text":"password"} onKeyDown={e=>e.key==="Enter"&&submit()}/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff size={15}/>:<Eye size={15}/>}</button></div><button className="accountPrimary" disabled={busy||!email||password.length<8} onClick={submit}>{ownerOnly||mode==="login"?"Login":"Create Account"}</button></>}{error&&<div className="accountError">{error}</div>}{info&&<div className="accountInfo">{info}</div>}<div className="accountNote"><ShieldCheck size={14}/> Free users ke liye daily media limits active hain. Upgrade payment baad mein enable kiya ja sakta hai.</div></div></div></div>
}