import React,{useEffect,useState}from"react";
import{X,UserCircle,LogIn,UserPlus,LogOut,Wallet,ShieldCheck,Crown,CheckCircle}from"lucide-react";
const API_BASE="https://bhai-ai-vpna.onrender.com";
const api=p=>API_BASE+p;
export default function AccountPanel({onClose,onAccount}){
 const[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[account,setAccount]=useState(null),[ledger,setLedger]=useState([]),[plans,setPlans]=useState([]),[active,setActive]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[info,setInfo]=useState("");
 const token=()=>sessionStorage.getItem("bhai_user_session")||"";
 async function billing(){const t=token();if(!t)return;try{const r=await fetch(api("/api/billing?plans=1"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok)setPlans(d.plans||[]);const s=await fetch(api("/api/billing"),{headers:{Authorization:"Bearer "+t}});const sd=await s.json();if(s.ok)setActive(sd.active||null)}catch{}}
 async function load(){const t=token();if(!t)return;try{const r=await fetch(api("/api/accounts?me=1"),{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(r.ok){setAccount(d.account);onAccount?.(d.account);const lr=await fetch(api("/api/accounts?ledger=1"),{headers:{Authorization:"Bearer "+t}});const ld=await lr.json();setLedger(ld.ledger||[]);billing()}else{sessionStorage.removeItem("bhai_user_session")}}catch{}}
 useEffect(()=>{load()},[]);
 async function submit(){setBusy(true);setError("");setInfo("");try{const action=mode==="login"?"login":"register";const r=await fetch(api("/api/accounts"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");if(action==="register"){setInfo("Account created. Ab login karo.");setMode("login");setPassword("")}else{sessionStorage.setItem("bhai_user_session",d.session);setAccount(d.account);onAccount?.(d.account);setInfo("Login successful.");billing()}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function logout(){const t=token();if(t)await fetch(api("/api/accounts"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})}).catch(()=>{});sessionStorage.removeItem("bhai_user_session");setAccount(null);setActive(null);onAccount?.(null);setInfo("Logged out.")}
 async function upgrade(plan){
  setBusy(true);setError("");setInfo("");
  try{
   const t=token();const r=await fetch(api("/api/billing"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action:"create_order",planId:plan.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Payment setup failed");
   await new Promise((resolve,reject)=>{const done=()=>{if(window.Razorpay)return resolve();reject(new Error("Payment checkout load failed"))};if(window.Razorpay)return done();const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=done;s.onerror=()=>reject(new Error("Payment checkout load failed"));document.body.appendChild(s)});
   const rz=new window.Razorpay({key:d.keyId,amount:d.order.amount,currency:d.order.currency,name:"BHAI X",description:plan.name,order_id:d.order.id,theme:{color:"#111827"},handler:async response=>{try{const vr=await fetch(api("/api/billing"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action:"verify",planId:plan.id,...response})});const vd=await vr.json();if(!vr.ok)throw new Error(vd.error||"Payment verification failed");setActive(vd.subscription);setInfo("🎉 Payment verified — "+plan.name+" active hai.");}catch(e){setError(e.message)}finally{setBusy(false)}}});
   rz.on("payment.failed",x=>{setError(x.error?.description||"Payment failed");setBusy(false)});rz.open();
  }catch(e){setError(e.message);setBusy(false)}
 }
 return <div className="panelOverlay"><div className="utilityPanel accountPanel"><div className="utilityHead"><div><b>👤 BHAI X Account</b><span>Login, subscription and account access</span></div><button onClick={onClose}><X/></button></div><div className="utilityBody">{account?<><div className="accountHero"><div className="accountAvatar"><UserCircle/></div><div><b>{account.email}</b><span>{account.role} • {account.blocked?"BLOCKED":"ACTIVE"}</span></div></div><div className="creditCard"><Wallet/><div><span>Credits</span><b>{account.credits}</b></div></div>{active?<div className="creditCard"><Crown/><div><span>Current Plan</span><b>{active.plan_name}</b><small>Valid till {new Date(active.expires_at).toLocaleDateString()}</small></div></div>:null}<div className="subscriptionBox"><div className="subscriptionTitle"><Crown size={18}/><b>Upgrade BHAI X</b></div><div className="planGrid">{plans.map(p=><div className="planCard" key={p.id}><b>{p.name}</b><strong>₹{p.amount}</strong><span>{p.days} days access</span><button disabled={busy} onClick={()=>upgrade(p)}>Upgrade</button><small><CheckCircle size={12}/> Secure checkout</small></div>)}</div></div><div className="accountLedger"><b>Credit Ledger</b>{ledger.length?ledger.map(x=><div key={x.id}><span>{x.reason||"Credit adjustment"}</span><strong>{x.amount>0?"+":""}{x.amount}</strong></div>):<span>No transactions yet.</span>}</div><button className="accountLogout" onClick={logout}><LogOut size={15}/> Logout</button></>:<><div className="accountTabs"><button className={mode==="login"?"active":""} onClick={()=>{setMode("login");setError("");setInfo("")}}><LogIn size={14}/> Login</button><button className={mode==="register"?"active":""} onClick={()=>{setMode("register");setError("");setInfo("")}}><UserPlus size={14}/> Register</button></div><input className="accountInput" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input className="accountInput" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" type="password" onKeyDown={e=>e.key==="Enter"&&submit()}/><button className="accountPrimary" disabled={busy||!email||password.length<8} onClick={submit}>{mode==="login"?"Login":"Create Account"}</button></>}{error&&<div className="accountError">{error}</div>}{info&&<div className="accountInfo">{info}</div>}<div className="accountNote"><ShieldCheck size={14}/> Payment secrets server par protected hain; owner controls yahan se change nahi hote.</div></div></div></div>
}