import crypto from "node:crypto";
import { generateSelfHostedLipSync } from "./selfHostedMediaProvider.js";

export const CHARACTER_LIPSYNC_SCHEMA_VERSION = "1.0";
export const DEFAULT_CHARACTER_LIPSYNC_MODEL = "lipsync-2";
const MAX_MEDIA_BYTES = 24 * 1024 * 1024;
const clean = (value, max = 500) => String(value ?? "").trim().slice(0, max);

function decodeMedia(data, label) {
  const bytes = Buffer.from(String(data || ""), "base64");
  if (!bytes.length) throw new Error("Lip-sync input " + label + " is empty.");
  if (bytes.length > MAX_MEDIA_BYTES) throw new Error("Lip-sync input " + label + " exceeds the 24 MB limit.");
  return bytes;
}

function assertMp4(bytes, label) {
  if (bytes.length < 32 || bytes.subarray(4, 8).toString("ascii") !== "ftyp") {
    throw new Error(label + " is not a verified MP4 container.");
  }
}

function assertWav(bytes) {
  if (bytes.length < 46 || bytes.subarray(0, 4).toString("ascii") !== "RIFF" ||
      bytes.subarray(8, 12).toString("ascii") !== "WAVE") {
    throw new Error("Lip-sync audio must be a valid WAV generated by character TTS.");
  }
}

function fitWavDuration(bytes, durationSeconds) {
  const target = Number(durationSeconds);
  if (!Number.isFinite(target) || target <= 0) return bytes;
  if (target > 30) throw new Error("Lip-sync scene duration exceeds the 30 second per-scene limit.");
  const sampleRate = bytes.readUInt32LE(24);
  const channels = bytes.readUInt16LE(22);
  const bits = bytes.readUInt16LE(34);
  const format = bytes.readUInt16LE(20);
  const dataSize = bytes.readUInt32LE(40);
  if (format !== 1 || bits !== 16 || !sampleRate || !channels || bytes.length < 44) {
    throw new Error("Lip-sync audio must use verified 16-bit PCM WAV audio.");
  }
  const pcm = bytes.subarray(44, Math.min(bytes.length, 44 + dataSize));
  const bytesPerSecond = sampleRate * channels * (bits / 8);
  const targetBytes = Math.max(2, Math.floor(target * bytesPerSecond));
  const alignedTarget = targetBytes - (targetBytes % (channels * (bits / 8)));
  const fitted = pcm.length > alignedTarget
    ? pcm.subarray(0, alignedTarget)
    : Buffer.concat([pcm, Buffer.alloc(alignedTarget - pcm.length)]);
  const header = Buffer.alloc(44);
  header.write("RIFF", 0); header.writeUInt32LE(36 + fitted.length, 4);
  header.write("WAVE", 8); header.write("fmt ", 12); header.writeUInt32LE(16, 16);
  header.writeUInt16LE(1, 20); header.writeUInt16LE(channels, 22);
  header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(bytesPerSecond, 28);
  header.writeUInt16LE(channels * (bits / 8), 32); header.writeUInt16LE(bits, 34);
  header.write("data", 36); header.writeUInt32LE(fitted.length, 40);
  return Buffer.concat([header, fitted]);
}

async function parseJson(response) {
  return await response.json().catch(() => ({}));
}

export async function generateCharacterLipSync(input = {}, options = {}) {
  const selfHostedEndpoint = clean(options.endpoint ?? process.env.BHAI_LIPSYNC_URL ?? "", 2000);
  if (selfHostedEndpoint) {
    return generateSelfHostedLipSync(input, { ...options, endpoint: selfHostedEndpoint, apiKey: options.apiKey ?? process.env.BHAI_LIPSYNC_API_KEY ?? "" });
  }
  const apiKey = clean(options.apiKey ?? process.env.SYNC_API_KEY ?? "");
  if (!apiKey) throw new Error("SYNC_API_KEY is not configured; real video lip-sync is unavailable.");
  const fetchImpl = options.fetchImpl || globalThis.fetch;
  if (typeof fetchImpl !== "function") throw new Error("Fetch is unavailable for lip-sync.");
  const videoBytes = decodeMedia(input.videoData, "video");
  let audioBytes = decodeMedia(input.audioData, "audio");
  assertMp4(videoBytes, "Lip-sync source video");
  assertWav(audioBytes);
  if (Number(input.durationSeconds) > 0) audioBytes = fitWavDuration(audioBytes, input.durationSeconds);
  const model = clean(options.model || process.env.SYNC_LIPSYNC_MODEL || DEFAULT_CHARACTER_LIPSYNC_MODEL, 80);
  const form = new FormData();
  form.set("model", model);
  form.set("video", new Blob([videoBytes], { type: clean(input.videoMimeType || "video/mp4", 100) }), "character.mp4");
  form.set("audio", new Blob([audioBytes], { type: "audio/wav" }), "character-voice.wav");
  const idempotencyKey = crypto.createHash("sha256")
    .update([input.sceneId || "", input.videoHash || crypto.createHash("sha256").update(videoBytes).digest("hex"),
      input.audioHash || crypto.createHash("sha256").update(audioBytes).digest("hex"), model].join("|"))
    .digest("hex").slice(0, 64);
  const timeoutMs = Number(options.timeoutMs) > 0 ? Number(options.timeoutMs) : 180000;
  const signal = options.signal || AbortSignal.timeout(timeoutMs);
  const createdResponse = await fetchImpl("https://api.sync.so/v2/generate", {
    method: "POST",
    headers: { "x-api-key": apiKey, "Idempotency-Key": idempotencyKey },
    body: form,
    signal
  });
  let job = await parseJson(createdResponse);
  if (!createdResponse.ok) {
    throw new Error("Lip-sync provider returned HTTP " + createdResponse.status + ": " +
      clean(job?.message || job?.error || job?.errorMessage || "Generation request failed."));
  }
  const jobId = clean(job.id || job.generationId, 160);
  if (!jobId) throw new Error("Lip-sync provider did not return a generation ID.");
  const sleep = options.sleepImpl || (ms => new Promise(resolve => setTimeout(resolve, ms)));
  const maxPolls = Math.max(1, Math.min(90, Number(options.maxPolls) || 45));
  for (let poll = 0; poll < maxPolls && !["COMPLETED", "FAILED", "REJECTED"].includes(String(job.status || "").toUpperCase()); poll++) {
    if (poll) await sleep(Math.max(0, Number(options.pollIntervalMs ?? 2000)));
    const statusResponse = await fetchImpl("https://api.sync.so/v2/generate/" + encodeURIComponent(jobId), {
      method: "GET", headers: { "x-api-key": apiKey }, signal
    });
    job = await parseJson(statusResponse);
    if (!statusResponse.ok) {
      throw new Error("Lip-sync status request returned HTTP " + statusResponse.status + ".");
    }
  }
  const status = String(job.status || "").toUpperCase();
  if (status !== "COMPLETED") {
    throw new Error(status === "FAILED" || status === "REJECTED"
      ? "Lip-sync provider job " + status.toLowerCase() + ": " + clean(job.error || job.errorMessage || "No provider detail.")
      : "Lip-sync provider job did not finish before the polling deadline.");
  }
  const outputUrl = clean(job.outputUrl || job.output_url || job.output?.url || job.segmentOutputUrl, 2000);
  if (!/^https:\/\//i.test(outputUrl)) throw new Error("Completed lip-sync job has no HTTPS output URL.");
  const outputResponse = await fetchImpl(outputUrl, { method: "GET", signal });
  if (!outputResponse.ok) throw new Error("Lip-sync output download returned HTTP " + outputResponse.status + ".");
  const outputBytes = Buffer.from(await outputResponse.arrayBuffer());
  if (!outputBytes.length || outputBytes.length > MAX_MEDIA_BYTES) {
    throw new Error("Lip-sync output is empty or exceeds the 24 MB renderer limit.");
  }
  assertMp4(outputBytes, "Lip-sync output");
  const outputDuration = Number(job.outputDuration || job.output_duration || input.durationSeconds || 0) || null;
  if (Number(input.durationSeconds) > 0 && outputDuration &&
      Math.abs(outputDuration - Number(input.durationSeconds)) > Math.max(1.5, Number(input.durationSeconds) * 0.2)) {
    throw new Error("Lip-sync output duration differs materially from the requested scene duration.");
  }
  return {
    mimeType: "video/mp4",
    data: outputBytes.toString("base64"),
    duration: outputDuration,
    provider: "sync.so/" + model,
    verification: {
      ok: true,
      mode: "provider-completed-lipsync-mp4",
      provider: "sync.so",
      providerJobId: jobId,
      model,
      status,
      bytes: outputBytes.length,
      containerValid: true,
      pixelLipSyncVerified: false
    }
  };
}
