import crypto from "node:crypto";
import {getDb,initDb} from "./db.js";
const json=(res,s,d)=>res.status(s).json(d);
const hash=s=>crypto.createHash("sha256").update(String(s)).digest("hex");
function ownerOk(req){const expected=process.env.OWNER_ACCESS_KEY,supplied=req.headers?.["x-owner-key"]||"";if(!expected||!supplied)return false;const a=Buffer.from(String(expected)),b=Buffer.from(String(supplied));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
async function schema(db){await db.query("CREATE TABLE IF NOT EXISTS bhai_accounts (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',credits INTEGER NOT NULL DEFAULT 0,blocked BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");await db.query("CREATE TABLE IF NOT EXISTS bhai_credit_ledger (id TEXT PRIMARY KEY,account_id TEXT NOT NULL,amount INTEGER NOT NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");await db.query("CREATE TABLE IF NOT EXISTS bhai_sessions (token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");}
async function session(req,db){const t=String(req.headers?.authorization||"").replace(/^Bearer\s+/i,"").trim();if(!t)return null;const h=hash(t);const r=await db.query("SELECT a.id,a.email,a.role,a.credits,a.blocked FROM bhai_sessions s JOIN bhai_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>NOW()",[h]);const a=r.rows[0];if(!a||a.blocked)return null;return a;}
export default async function handler(req,res){
 await initDb().catch(()=>false);const db=await getDb();if(!db)return json(res,503,{error:"DATABASE_URL is required"});await schema(db);
 if(req.method==="POST"){
  const action=String(req.body?.action||"");
  if(action==="register"){const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return json(res,400,{error:"Valid email and password(8+) required"});const id=crypto.randomUUID();try{await db.query("INSERT INTO bhai_accounts(id,email,password_hash) VALUES($1,$2,$3)",[id,email,hash(password)]);}catch{return json(res,409,{error:"Account already exists"});}return json(res,201,{ok:true,account:{id,email,role:"user",credits:0}});}
  if(action==="login"){const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");const r=await db.query("SELECT id,email,role,credits,blocked FROM bhai_accounts WHERE email=$1 AND password_hash=$2",[email,hash(password)]);const a=r.rows[0];if(!a||a.blocked)return json(res,401,{error:"Invalid or blocked account"});const token=crypto.randomBytes(32).toString("hex");await db.query("INSERT INTO bhai_sessions(token_hash,account_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')",[hash(token),a.id]);return json(res,200,{ok:true,account:a,session:token});}
  if(action==="logout"){const a=await session(req,db);if(a){const t=String(req.headers.authorization).replace(/^Bearer\s+/i,"").trim();await db.query("DELETE FROM bhai_sessions WHERE token_hash=$1",[hash(t)]);}return json(res,200,{ok:true});}
  if(action==="me"){const a=await session(req,db);if(!a)return json(res,401,{error:"Unauthorized"});return json(res,200,{ok:true,account:a});}
  if(action==="credit"){if(!ownerOk(req))return json(res,401,{error:"Owner authorization required."});const id=String(req.body?.accountId||""),amount=Number(req.body?.amount);if(!id||!Number.isInteger(amount)||amount===0)return json(res,400,{error:"accountId and non-zero integer amount required"});const r=await db.query("UPDATE bhai_accounts SET credits=GREATEST(credits+$2,0) WHERE id=$1 RETURNING id,email,credits,blocked",[id,amount]);if(!r.rows[0])return json(res,404,{error:"Account not found"});await db.query("INSERT INTO bhai_credit_ledger(id,account_id,amount,reason) VALUES($1,$2,$3,$4)",[crypto.randomUUID(),id,amount,String(req.body?.reason||"admin adjustment")]);return json(res,200,{ok:true,account:r.rows[0],amount});}
  if(action==="block"){if(!ownerOk(req))return json(res,401,{error:"Owner authorization required."});const id=String(req.body?.accountId||"");const r=await db.query("UPDATE bhai_accounts SET blocked=NOT blocked WHERE id=$1 RETURNING id,email,blocked",[id]);if(!r.rows[0])return json(res,404,{error:"Account not found"});return json(res,200,{ok:true,account:r.rows[0]});}
 }
 if(req.method==="GET"){if(req.query?.me==="1"){const a=await session(req,db);return a?json(res,200,{ok:true,account:a}):json(res,401,{error:"Unauthorized"});}if(req.query?.role==="admin"){if(!ownerOk(req))return json(res,401,{error:"Owner authorization required."});const r=await db.query("SELECT id,email,role,credits,blocked,created_at FROM bhai_accounts ORDER BY created_at DESC LIMIT 200");return json(res,200,{ok:true,accounts:r.rows});}return json(res,400,{error:"Unsupported query"});}
 return json(res,405,{error:"Method not allowed"});
}