import crypto from "node:crypto";
import {getDb,initDb} from "./db.js";
const json=(res,s,d)=>res.status(s).json(d);
const hash=s=>crypto.createHash("sha256").update(String(s)).digest("hex");
const scryptAsync=(password,salt)=>new Promise((resolve,reject)=>crypto.scrypt(String(password),salt,64,{N:16384,r:8,p:1,maxmem:32*1024*1024},(e,k)=>e?reject(e):resolve(k.toString("hex"))));
async function makePassword(password){const salt=crypto.randomBytes(16).toString("hex");const key=await scryptAsync(password,salt);return "scrypt$"+salt+"$"+key;}
async function verifyPassword(password,stored){
 if(String(stored).startsWith("scrypt$")){const p=String(stored).split("$");if(p.length!==3)return false;const key=await scryptAsync(password,p[1]);return crypto.timingSafeEqual(Buffer.from(key,"hex"),Buffer.from(p[2],"hex"));}
 return hash(password)===String(stored);
}

function ownerOk(req){const e=process.env.OWNER_ACCESS_KEY,s=req.headers?.["x-owner-key"]||req.body?.ownerKey||"";if(!e||!s)return false;const a=Buffer.from(String(e)),b=Buffer.from(String(s));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
export default async function handler(req,res){
 await initDb().catch(()=>false);const db=await getDb();if(!db)return json(res,503,{error:"DATABASE_URL is required"});
 await db.query("CREATE TABLE IF NOT EXISTS bhai_resellers (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,balance INTEGER NOT NULL DEFAULT 0,blocked BOOLEAN NOT NULL DEFAULT FALSE,permissions TEXT NOT NULL DEFAULT '[]',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())"); await db.query("ALTER TABLE bhai_resellers ADD COLUMN IF NOT EXISTS permissions TEXT NOT NULL DEFAULT '[]'");
 await db.query("CREATE TABLE IF NOT EXISTS bhai_reseller_sessions (token_hash TEXT PRIMARY KEY,reseller_id TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
 await db.query("CREATE TABLE IF NOT EXISTS bhai_reseller_ledger (id TEXT PRIMARY KEY,reseller_id TEXT NOT NULL,amount INTEGER NOT NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
 async function resellerSession(){const t=String(req.headers?.authorization||"").replace(/^Bearer\\s+/i,"").trim();if(!t)return null;const r=await db.query("SELECT r.id,r.email,r.balance,r.blocked,r.permissions FROM bhai_reseller_sessions s JOIN bhai_resellers r ON r.id=s.reseller_id WHERE s.token_hash=$1 AND s.expires_at>NOW()",[hash(t)]);const x=r.rows[0];if(!x||x.blocked)return null;try{x.permissions=JSON.parse(x.permissions||"[]")}catch{x.permissions=[]}return x;}
 if(req.method==="POST"&&String(req.body?.action||"")==="login"){const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");const r=await db.query("SELECT id,email,balance,blocked,permissions,password_hash FROM bhai_resellers WHERE email=$1",[email]);const x=r.rows[0];if(!x||x.blocked||!(await verifyPassword(password,x.password_hash)))return json(res,401,{error:"Invalid or blocked reseller"});if(!String(x.password_hash).startsWith("scrypt$")){const nh=await makePassword(password);await db.query("UPDATE bhai_resellers SET password_hash=$2 WHERE id=$1",[x.id,nh]);}delete x.password_hash;const token=crypto.randomBytes(32).toString("hex");await db.query("INSERT INTO bhai_reseller_sessions(token_hash,reseller_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')",[hash(token),x.id]);try{x.permissions=JSON.parse(x.permissions||"[]")}catch{x.permissions=[]}return json(res,200,{ok:true,reseller:x,session:token});}
 if(req.method==="POST"&&String(req.body?.action||"")==="logout"){const t=String(req.headers?.authorization||"").replace(/^Bearer\\s+/i,"").trim();if(t)await db.query("DELETE FROM bhai_reseller_sessions WHERE token_hash=$1",[hash(t)]);return json(res,200,{ok:true});}
 if(req.method==="GET"&&req.query?.me==="1"){const x=await resellerSession();return x?json(res,200,{ok:true,reseller:x}):json(res,401,{error:"Unauthorized"});}
 if(req.method==="GET"&&req.query?.ledger==="1"){const x=await resellerSession();if(!x)return json(res,401,{error:"Unauthorized"});const r=await db.query("SELECT id,amount,reason,created_at FROM bhai_reseller_ledger WHERE reseller_id=$1 ORDER BY created_at DESC LIMIT 100",[x.id]);return json(res,200,{ok:true,ledger:r.rows});}
 if(!ownerOk(req))return json(res,401,{error:"Owner authorization required."});
 if(req.method==="GET"){const r=await db.query("SELECT id,email,balance,blocked,permissions,created_at FROM bhai_resellers ORDER BY created_at DESC");return json(res,200,{ok:true,resellers:r.rows});}
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
 const self=await resellerSession();
 const a=String(req.body?.action||"");
 if(self && ["balance","permissions","block","create"].includes(a))return json(res,403,{error:"Owner authorization required."});
 if(a==="create"){const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email||password.length<8)return json(res,400,{error:"email and password(8+) required"});try{const id=crypto.randomUUID();const permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>typeof x==="string").slice(0,20):[];await db.query("INSERT INTO bhai_resellers(id,email,password_hash,permissions) VALUES($1,$2,$3,$4)",[id,email,await makePassword(password),JSON.stringify(permissions)]);return json(res,201,{ok:true,reseller:{id,email,balance:0,blocked:false,permissions}})}catch{return json(res,409,{error:"Reseller already exists"})}}
 if(a==="block"){const id=String(req.body?.id||"");await db.query("UPDATE bhai_resellers SET blocked=NOT blocked WHERE id=$1",[id]);return json(res,200,{ok:true,id});}
 if(a==="balance"){const id=String(req.body?.id||""),amount=Number(req.body?.amount);if(!id||!Number.isInteger(amount)||amount===0)return json(res,400,{error:"id and non-zero integer amount required"});const r=await db.query("UPDATE bhai_resellers SET balance=GREATEST(balance+$2,0) WHERE id=$1 RETURNING balance",[id,amount]);if(!r.rows[0])return json(res,404,{error:"Reseller not found"});await db.query("INSERT INTO bhai_reseller_ledger(id,reseller_id,amount,reason) VALUES($1,$2,$3,$4)",[crypto.randomUUID(),id,amount,String(req.body?.reason||"owner adjustment")]);return json(res,200,{ok:true,id,balance:r.rows[0].balance});}
 if(a==="permissions"){const id=String(req.body?.id||""),permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(x=>typeof x==="string").slice(0,20):[];const r=await db.query("UPDATE bhai_resellers SET permissions=$2 WHERE id=$1 RETURNING id,email,permissions",[id,JSON.stringify(permissions)]);if(!r.rows[0])return json(res,404,{error:"Reseller not found"});try{r.rows[0].permissions=JSON.parse(r.rows[0].permissions||"[]")}catch{r.rows[0].permissions=[]}return json(res,200,{ok:true,reseller:r.rows[0]});}
 if(a==="ledger"){const id=String(req.body?.id||"");const r=await db.query("SELECT id,amount,reason,created_at FROM bhai_reseller_ledger WHERE reseller_id=$1 ORDER BY created_at DESC LIMIT 100",[id]);return json(res,200,{ok:true,ledger:r.rows});}
 return json(res,400,{error:"Unknown reseller action"});
}